// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ShlYOUygEQwXCqU10CnpbsGkEN8yXgE',
    appId: '1:112165943464:web:f1724b2e9c42cb1cb9aa9d',
    messagingSenderId: '112165943464',
    projectId: 'formflutter-5f8dd',
    authDomain: 'formflutter-5f8dd.firebaseapp.com',
    storageBucket: 'formflutter-5f8dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIAtf8-u0gDrp-gsMoLO8xXmYzwyRBnQ',
    appId: '1:112165943464:android:43f5a12d1f817a58b9aa9d',
    messagingSenderId: '112165943464',
    projectId: 'formflutter-5f8dd',
    storageBucket: 'formflutter-5f8dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoWJzDG-sONXAQGRqGccsqG8W6OrEzO4M',
    appId: '1:112165943464:ios:b2caad6e325af277b9aa9d',
    messagingSenderId: '112165943464',
    projectId: 'formflutter-5f8dd',
    storageBucket: 'formflutter-5f8dd.appspot.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoWJzDG-sONXAQGRqGccsqG8W6OrEzO4M',
    appId: '1:112165943464:ios:b2caad6e325af277b9aa9d',
    messagingSenderId: '112165943464',
    projectId: 'formflutter-5f8dd',
    storageBucket: 'formflutter-5f8dd.appspot.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6ShlYOUygEQwXCqU10CnpbsGkEN8yXgE',
    appId: '1:112165943464:web:d72bcec2865f77fcb9aa9d',
    messagingSenderId: '112165943464',
    projectId: 'formflutter-5f8dd',
    authDomain: 'formflutter-5f8dd.firebaseapp.com',
    storageBucket: 'formflutter-5f8dd.appspot.com',
  );

}