// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa56Lo5c3s5IFvsUq013FPFz8JZuK_3aI',
    appId: '1:496778702285:web:b4a78ee66775c6a786a884',
    messagingSenderId: '496778702285',
    projectId: 'form-eec11',
    authDomain: 'form-eec11.firebaseapp.com',
    storageBucket: 'form-eec11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKfqy8MJ1BFO2bA7IrHhrc2mQITanBysw',
    appId: '1:496778702285:android:f3e2a90c722336cc86a884',
    messagingSenderId: '496778702285',
    projectId: 'form-eec11',
    storageBucket: 'form-eec11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJflkjnEO3oeFIEtrQA5W7tbGD94DuG4',
    appId: '1:496778702285:ios:99e7399c14fb1c5486a884',
    messagingSenderId: '496778702285',
    projectId: 'form-eec11',
    storageBucket: 'form-eec11.appspot.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSJflkjnEO3oeFIEtrQA5W7tbGD94DuG4',
    appId: '1:496778702285:ios:99e7399c14fb1c5486a884',
    messagingSenderId: '496778702285',
    projectId: 'form-eec11',
    storageBucket: 'form-eec11.appspot.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa56Lo5c3s5IFvsUq013FPFz8JZuK_3aI',
    appId: '1:496778702285:web:2037d7e740cc8c9186a884',
    messagingSenderId: '496778702285',
    projectId: 'form-eec11',
    authDomain: 'form-eec11.firebaseapp.com',
    storageBucket: 'form-eec11.appspot.com',
  );
}
